[package]
name = "demon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
ctrlc = "3.4.7"
glob = "0.3.2"
notify = "8.0.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
